### ISSUE TITLE
Error executing vim.schedule lua callback: Vim(for):E714: List required 

### ISSUE THREAD

**Issue by DonnieWest** [neovim/nvim-lsp#102]
I'm running into the following error during completion using the `tsserver` configuration. Other forms of completion (`gopls`, `rust-lsp`, etc) all work

```
Error executing vim.schedule lua callback: Vim(for):E714: List required 
```

This was originally reported to me on my loose wrapper for nvim-lsp for asyncomplete on this issue: https://github.com/DonnieWest/asyncomplete_neovim_lsp/issues/1

I've since been able to replicate it on a small Javascript project, using the `tsserver` configuration and only using an omnifunc, so I was able to rule out my project.

I'm totally open to there being something wrong with how I'm configured. If I need more info, I'm happy to supply :)

**Comment by justinmk** [comment]
is there no line number/backtrace given?

**Comment by DonnieWest** [comment]
This is just what was printed to `:messages` - is there a better place that I can grab debugging info?

**Comment by justinmk** [comment]
I don't see anywhere in nvim core nor nvim-lsp where we schedule a VimL for-loop. Just a guess, but I see [this](https://github.com/DonnieWest/asyncomplete_neovim_lsp/blob/master/autoload/asyncomplete/sources/lsp.vim#L111) assumes that `a:results['items']` is a list. Maybe it's null or something like that?

I think we need better tracing for vim.schedule, but that's a core issue not nvim-lsp.

**Comment by DonnieWest** [comment]
Aha. Yep. That's the issue. Sorry for the noise
