### ISSUE TITLE
Error in clangd on Windows.

### ISSUE THREAD

**Issue by erw7** [neovim/nvim-lsp#113]
Due to changes in https://github.com/neovim/nvim-lsp/commit/638dad178311ee890b54587280790955eefd75ad, the following error occurs when opening a C source file on Windows:

```
E5108: Error executing lua shared.lua:427: root_dir: expected directory, got C:\msys64\home\erw7\src\github.com\neovim\neovim\src\nvim\tui\tui.c
```

On Windows, the following result does not seem to be `nil`.

```
vim.loop.fs_stat('C:\\Windows\\System32\\notepad.exe\\.')
```

I think that if we add `'.'` to `root_pattern` on non-Windows, it always returns the directory where the file is located.

**Comment by justinmk** [comment]
Thanks for debugging! So you have a local change that is working for you? Could you post it here?
