### ISSUE TITLE
What about coc-nvim?

### ISSUE THREAD

**Issue by NullVoxPopuli** [neovim/nvim-lsp#12]
What are this project's goals, and how do they differ from https://github.com/neoclide/coc.nvim ?
Will any of the got plugins be useable with whatever this approach is?

**Comment by justinmk** [comment]
This repo is a collection of configs.

Goal of Nvim LSP support is a best-effort reasonable LSP client with a well designed Lua API. 

Users can continue to use whatever they want.

> Will any of the got plugins be useable with whatever this approach is?

Assuming "got" means "coc"... No.
