### ISSUE TITLE
Crash when using rust-analyzer.

### ISSUE THREAD

**Issue by nabezokodaikon** [neovim/nvim-lsp#125]
## Environment Information
* OS: MAC
* NVIM: 0.5.0 `5d5b068`
* rust-analyzer: `5bf669860984a2c058b3bdc3e43b4993a0f25b31`
* nvim-lsp: `42385dbf6a5eac40da213322fdd3037588eede56`

## Provide a minimal settings
lsp.lua
```
vim.cmd('packadd nvim-lsp')
require'nvim_lsp'.rls.setup{}
require'nvim_lsp'.rust_analyzer.setup{}
```

## Error
```
Vim(lua):E5108: Error executing lua [string ":lua"]:1: attempt to index a boolean value
LSP[rust_analyzer] Failed to deserialize config: invalid length 0, expected struct ServerConfig with 12 elements; []
```

**Comment by h-michael** [comment]
see https://github.com/neovim/nvim-lsp/issues/94#issuecomment-584432418 and https://github.com/neovim/nvim-lsp/pull/121

**Comment by nabezokodaikon** [comment]
Solved on branch `h-michael / nvim-lsp`. Thank you.
