### ISSUE TITLE
question: more information with reference/implementation results

### ISSUE THREAD

**Issue by urandom** [neovim/nvim-lsp#129]
Hi,

Is there a way to configure nvim-lsp to show the line contents as well as the file:line:column in the quickfix?

At least by default, it seems to only show the filename information, which makes it quite hard to go where I need, since I don't know what is at those positions.

**Comment by h-michael** [comment]
https://github.com/neovim/neovim/pull/11910 will resolve this.

**Comment by h-michael** [comment]
This is a problem with the implementation of the lsp client itself, and I will close it because the above PR will probably solve it.
Please comment if you have anything.
