### ISSUE TITLE
Question: how can I possibly get a similar completion experience as e.g. coc.nvim?

### ISSUE THREAD

**Issue by K1DV5** [neovim/nvim-lsp#130]
I'm used to using coc.nvim style completion where the completion list is shown and updated as you type. But with omnifunc, you have to explicitly invoke it. Is there a workaround?

**Comment by h-michael** [comment]
I don't use coc.nvim. Would you show me gif or video?

**Comment by K1DV5** [comment]
![](https://s2.gifyu.com/images/autocomplete.gif)

**Comment by Shatur95** [comment]
![изображение](https://user-images.githubusercontent.com/22453358/74836884-f6a49580-5328-11ea-9306-1a70bcd8b374.png)

**Comment by mjlbach** [comment]
@K1DV5 For now, you'll need to use an auto-completion plugin (although I'm hacking on a built-in lua solution because I would love to reduce my plugin count by 1)

I would recommend either:
https://github.com/Shougo/deoplete.nvim 
https://github.com/Shougo/deoplete-lsp

https://github.com/ncm2/ncm2

I would currently not recommend:
https://github.com/lifepillar/vim-mucomplete

**Comment by Shatur95** [comment]
@mjlbach, thank you!
So, auto-completion will be build-in in `vim-lsp` in future?

**Comment by lithammer** [comment]
> https://github.com/lifepillar/vim-mucomplete

I'm a fan of this. However it probably doesn't work the way you want/expect. I like the fact that it has a trigger (`<Tab>` in my case) instead of just popping up all the time causing a bunch of visual noise as you type.

**Comment by mjlbach** [comment]
> > https://github.com/lifepillar/vim-mucomplete
> 
> I'm a fan of this. However it probably doesn't work the way you want/expect. I like the fact that it has a trigger (`<Tab>` in my case) instead of just popping up all the time causing a bunch of visual noise as you type. But that's subjective, I suppose.

In my case, it does in fact popup immediately after a trigger character (., :) etc.

**Comment by Shatur95** [comment]
> I'm a fan of this.

Sorry for a dump questions, how do you configured it with vim-lsp?

**Comment by mjlbach** [comment]
These are all of the relevant lsp settings in my init.vim, including mucomplete.
```
" " Set up pyls
" /Users/michael/.local/share/nvim/vim-lsp.log
:lua << EOF
  local nvim_lsp = require 'nvim_lsp'
  do
  local method = 'textDocument/publishDiagnostics'
  local default_callback = vim.lsp.callbacks[method]
  vim.lsp.callbacks[method] = function(err, method, result, client_id)
    default_callback(err, method, result, client_id)
    if result and result.diagnostics then
      for _, v in ipairs(result.diagnostics) do
        v.uri = v.uri or result.uri
      end
      vim.lsp.util.set_qflist(result.diagnostics)
      end
    end
  end
  nvim_lsp.gopls.setup({})
  nvim_lsp.jsonls.setup({})
  nvim_lsp.pyls_ms.setup({})
  nvim_lsp.vimls.setup({})
  nvim_lsp.sumneko_lua.setup({})
  nvim_lsp.rust_analyzer.setup({})
EOF

" set up keybindings
augroup Completion
  autocmd Filetype rust,python,go,c,cpp,vim,lua,json setl omnifunc=v:lua.vim.lsp.omnifunc
  autocmd CompleteDone * pclose
augroup end
nnoremap <silent> gD    <cmd>lua vim.lsp.buf.declaration()<CR>
nnoremap <silent> gd <cmd>lua vim.lsp.buf.definition()<CR>
nnoremap <silent> K     <cmd>lua vim.lsp.buf.hover()<CR>
nnoremap <silent> gi    <cmd>lua vim.lsp.buf.implementation()<CR>
nnoremap <silent> <c-k> <cmd>lua vim.lsp.buf.signature_help()<CR>
nnoremap <silent> <leader>D   <cmd>lua vim.lsp.buf.type_definition()<CR>
nnoremap <silent> <leader>rn   <cmd>lua vim.lsp.buf.rename()<CR>
nnoremap <silent> grf   <cmd>lua vim.lsp.buf.references()<CR>
command! Format  execute 'lua vim.lsp.buf.formatting()'

let g:mucomplete#enable_auto_at_startup = 1
set completeopt+=noinsert,noselect
```

**Comment by lithammer** [comment]
> Sorry for a dump questions, how do you configured it with vim-lsp?

You just need to make sure `omnifunc` is set to `v:lua.vim.lsp.omnifunc`.

@mjlbach I would suggest you use the `on_attach` callback. It's more dynamic since you don't have to hardcode the filetypes in your `autocmd` and doesn't create global mappings (i.e. plays nicer with non-lsp filetypes). Something like this:

```lua
local nvim_lsp = require('nvim_lsp')

local on_attach = function(_, bufnr)
  vim.api.nvim_buf_set_option(bufnr, 'omnifunc', 'v:lua.vim.lsp.omnifunc')

  -- Mappings.
  local opts = { noremap=true, silent=true }
  vim.api.nvim_buf_set_keymap(bufnr, 'n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
  vim.api.nvim_buf_set_keymap(bufnr, 'n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
  vim.api.nvim_buf_set_keymap(bufnr, 'n', ',rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
  vim.api.nvim_buf_set_keymap(bufnr, 'n', '[I', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
  vim.api.nvim_buf_set_keymap(bufnr, 'n', ',e', '<cmd>lua vim.lsp.util.show_line_diagnostics()<CR>', opts)
end

local servers = {'gopls', 'rust_analyzer', 'sumneko_lua', 'tsserver'}
for _, lsp in ipairs(servers) do
  nvim_lsp[lsp].setup {
    on_attach = on_attach,
  }
end
```

**Comment by Shatur95** [comment]
> You just need to make sure omnifunc is set to v:lua.vim.lsp.omnifunc.

Hm... I tried this with this configuration:
```vim
set completeopt+=menuone
set completeopt+=noinsert
let g:mucomplete#enable_auto_at_startup = 1
set omnifunc=v:lua.vim.lsp.omnifunc
```
MUcomplete works, but I do not have LSP suggestions. Tested with Python. I have `pyls` installed and neovim  v0.5.0-387-ge8f160c82`.

**Comment by mjlbach** [comment]
@lithammer Thanks, implemented your suggestions :)

**Comment by Shatur95** [comment]
> @Shatur95, can you get suggestions when you manually trigger omnifunc? 

How can I do it?
I newbie in Vim :)

**Comment by mjlbach** [comment]
> > @Shatur95, can you get suggestions when you manually trigger omnifunc?
> 
> How can I do it?
> I newbie in Vim :)

<c-x><c-o>

**Comment by Shatur95** [comment]
> <c-x><c-o>

Yes, it show me LSP suggestins! How can I integrate it with MUcomplete?

**Comment by Shatur95** [comment]
@mjlbach, @lithammer, thank you a lot, I had a typo in Lua. Now everything works.
Is it possible to configure it with less Lua scripting as it done in `coc.nvim` or 
`LanguageClient-neovim`?

**Comment by mjlbach** [comment]
You can look at the original edit of my comment before revised, but there will always be at least three lines in a lua heredoc

**Comment by Shatur95** [comment]
@mjlbach, thanks, tested deoplete.nvim and ncm2, but I liked MUcomplete more.
I suggest to add this instructions in README.md.

**Comment by h-michael** [comment]
Thanks to everyone for suggesting various ways to address this issue.
@K1DV5 Do these answers solve your problem?Do these answers solve your problem?

**Comment by K1DV5** [comment]
Thank you so much, the biggest reason for me to switch from coc, which works great, is the fact that it depends on node. So since both deoplete and ncm2 rely on python, they're not viable. But mucomplete seems to be what I'm looking for. It's great. So thanks.

Should I close this or keep it open in case someone else has something to say?

**Comment by h-michael** [comment]
> Should I close this or keep it open in case someone else has something to say?
If we do not lock an issue, even if we close it, we can comment on the issue so close it.

**Comment by mjlbach** [comment]
@h-michael it might be convenient to start populating the wiki with some of these tips/tricks from various github issue

**Comment by justinmk** [comment]
> start populating the wiki

Let's avoid yet another source of truth. If there is really something actionable here, please send a doc update (to `runtime/doc/lsp.txt` in Neovim core repo). We already have too many documentation stores, we are trying to consolidate them.

**Comment by Shatur95** [comment]
@justinmk, thank you, didn't know about this page.
I changed my configuration to this:
```vim
packadd nvim-lsp
:lua << EOF
  local nvim_lsp = require('nvim_lsp')
  nvim_lsp.pyls.setup{}
  nvim_lsp.gdscript.setup{}
  nvim_lsp.clangd.setup{}
EOF

nnoremap <silent> gD <cmd>lua vim.lsp.buf.declaration()<CR>
nnoremap <silent> gd <cmd>lua vim.lsp.buf.definition()<CR>
nnoremap <silent> K <cmd>lua vim.lsp.buf.hover()<CR>
nnoremap <silent> gi <cmd>lua vim.lsp.buf.implementation()<CR>
nnoremap <silent> <C-,> <cmd>lua vim.lsp.buf.signature_help()<CR>
nnoremap <silent> <leader>D <cmd>lua vim.lsp.buf.type_definition()<CR>
nnoremap <silent> gr <cmd>lua vim.lsp.buf.references()<CR>
au VimEnter * au FileType python,gdscript3,cpp setlocal omnifunc=v:lua.vim.lsp.omnifunc
```

**Comment by K1DV5** [comment]
I found mucomplete a little buggy and also felt that it does way more than what I need. So I made my own way:
```viml
function! Complete(direction) "{{{
    " direction: 1-forward, 2-backward, 0-show
    if pumvisible()
        if a:direction
            if a:direction == 1 "without shift, forward
                return "\<c-n>"
            endif
            " with shift, back
            return "\<c-p>"
        endif
    endif
    let chars = 2  " chars before triggering
    let pattern = '\(\w\|\d\)\{' . chars . '}'
    let col = col('.') - 1
    let line = getline('.')
    let last_chars = line[col-chars:col-1]
    if !a:direction && last_chars !~# pattern || !col || last_chars[-1] =~ '\s'
        " not at a completeable place
        return "\<tab>"
    endif
    " prevent keyword completion from making nvim unresponsive
    " check th[es]e| chars for previous attempts
    let before_match = line[col-chars-1:col-2]
    if !a:direction && len(before_match) && before_match =~# pattern
        return ''
    endif
    call feedkeys("\<c-n>")  " keyword completion
    if &omnifunc == 'v:lua.vim.lsp.omnifunc'  " lsp
        execute 'call' &omnifunc . '(0, "")'
    endif
    return ''
endfunction

" manual completion and cycling
imap <expr> <tab> Complete(1)
imap <expr> <s-tab> Complete(-1)
smap <expr> <tab> Complete(1)

" automatic completion
autocmd TextChangedI * call Complete(0)
```

* It shows suggestions from keyword completion first and requests omnifunc. If the omnifunc has any suggestions, the menu will be updated.
* It is triggered after at least two characters. But that can be changed by changing `chars`.
* At any time, if suggestions are not shown, you can make a request by using `<tab>`.

**Comment by Shatur95** [comment]
The only thing I missing is braces auto-insertion for methods. Is this LSP feature?

**Comment by K1DV5** [comment]
I think so, yes.

**Comment by mirageglobe** [comment]
to activate omnicomplete as you type without plugins. if that helps someone

```
" triggers completion without plugins
" https://stackoverflow.com/questions/35837990/how-to-trigger-omnicomplete-auto-completion-on-keystrokes-in-insert-mode

function! OpenCompletion()
  if !pumvisible() && ((v:char >= 'a' && v:char <= 'z') || (v:char >= 'A' && v:char <= 'Z'))
    call feedkeys("\<C-x>\<C-o>", "n")
  endif
endfunction

" uncomment line to enable omnicomplete
autocmd InsertCharPre * call OpenCompletion()
```

**Comment by mirageglobe** [comment]
i have a question despite above working well. when we do completion, i.e. selecting one of the options in popup, there is a suggestion which opens up a stratchboard in vim on the top. Any comments/hints or what that is or how its best to change how it shows the details of suggestion?

**Comment by clason** [comment]
The issue tracker is not a discussion forum; please ask usage questions on https://neovim.discourse.group.
