### ISSUE TITLE
Formatting with prettier

### ISSUE THREAD

**Issue by sparkcanon** [neovim/nvim-lsp#135]
Sorry if this is a dumb questions. I have been using `vim.lsp.buf.formatting()` but I don't think it respects my prettier or eslint rules. How do I make `vim.lsp.buf.formatting()` use my prettier rules?

Thanks!

**Comment by h-michael** [comment]
What language server do you use?

**Comment by justinmk** [comment]
This repo is a best-effort collection of configs. We can't answer questions about the hundreds of different ecosystems out there, it's up to user to send improvements here.

**Comment by sparkcanon** [comment]
@h-michael I am using tsserver.
@justinmk fair play.

**Comment by kaykhancheckpoint** [comment]
@sparkcanon Did you figure this out?

**Comment by mjlbach** [comment]
If you want to ask questions, I recommend you use our [discourse](discourse.neovim.io). Most people are using EFM as far as I can see for using prettier.

**Comment by 205g0** [comment]
@sparkcanon did you get it working? Afaik tsserver has its own (and by far the fastest) formatter out there, the api has two command types: `format` and `formatonkey`: https://github.com/microsoft/TypeScript/blob/6459ee4e4a3fa137089ab57491ca176089e3ff07/lib/protocol.d.ts#L24

**Comment by jrock2004** [comment]
> @sparkcanon did you get it working? Afaik tsserver has its own (and by far the fastest) formatter out there which is used by coc out of the box, the tsserver api has two command types: `format` and `formatonkey`: https://github.com/microsoft/TypeScript/blob/6459ee4e4a3fa137089ab57491ca176089e3ff07/lib/protocol.d.ts#L24
> 
> Edit: Ok found it, it seems that `vim.lsp.buf.formatting...` is supporting the built-in formatter, now the q how to get it formatting on key...

Did you ever get it to work? If so, how?
