### ISSUE TITLE
diagnostic doesn't refresh when switching buffers

### ISSUE THREAD

**Issue by haorenW1025** [neovim/nvim-lsp#151]
- `nvim --version`: NVIM v0.5.0-378-gbb331a9b3-dirty
- nvim-lsp version: newest
- Operating system/version: Mac
- Terminal name/version: Alacritty 0.4.0
- `$TERM`: xterm-256color

### How to reproduce the problem from neovim startup
I'm modifying the callback function to show diagnostic from location list like this
```
    if result and result.diagnostics then
      for _, v in ipairs(result.diagnostics) do
        v.uri = v.uri or result.uri
      end
    end
    vim.lsp.util.set_loclist(result.diagnostics)
```

### Actual behaviour
I've found out that when switch between buffers, location list won't 
renew automatically. So when I try to jump through location list, I will jump back
to the previous buffers. Right now I set an autocmd to Bufenter and use `:edit` to
renew buffer, but when jumping to changed but not saved buffers this will cause error.

### Expected behaviour
When Switch between buffers, diagnostics should be refresh. Is there some way to 
achieve this behaviour by modifying callback function? I'm eager to know! Thanks in
advance!

**Comment by mhartington** [comment]
@haorenW1025 I think this more of a neovim bug than an bug with this plugin. As the readme state, this is just a collection of lsp configs, not the actual lsp engine itself.

I'd suggest closing this here and opening an issue on neovim

**Comment by haorenW1025** [comment]
Oh that actually make sense. Thanks a lot for the reply anyway.
