### ISSUE TITLE
Language server for R

### ISSUE THREAD

**Issue by hhoeflin** [neovim/nvim-lsp#152]
Really looking forward to this. I use R a lot, so support for the language server for R would be great.

https://cran.r-project.org/web/packages/languageserver/index.html

P.S. Rls is not a good name for the Rust language server config; I thought that would be for R.

Thanks

**Comment by justinmk** [comment]
Send a PR. It's up to users to send configs here, we can't possibly manage configs for every ecosystem out there.

**Comment by hhoeflin** [comment]
Ok - will look into it. But I still suggest to rename the lsp-server config that is currently there for rust, e.g. from rls to rustls

**Comment by justinmk** [comment]
> But I still suggest to rename the lsp-server config that is currently there for rust, e.g. from rls to rustls

rls was rust's choice. But I agree, it's confusing. PR welcome!

**Comment by phelipetls** [comment]
I managed to get it working with this

```lua
local nvim_lsp = require'nvim_lsp'
local configs = require'nvim_lsp/configs'

if not configs.rlanguageserver then
  configs.rlanguageserver = {
    default_config = {
      cmd = {"R", "--slave", "-e", "languageserver::run()"};
      filetypes = {"r", "rmd"};
      root_dir = function(fname)
        return nvim_lsp.util.find_git_ancestor(fname) or vim.loop.os_homedir()
      end;
      log_level = vim.lsp.protocol.MessageType.Warning;
      settings = {};
    }
  }
end

nvim_lsp.rlanguageserver.setup{}
```

If this is fine, I'll try to make a pull request soon.

**Comment by dlukes** [comment]
@phelipetls Thanks, that helped me out as well! Maybe try starting that pull request and move the discussion there?
