### ISSUE TITLE
Can't override default config values in setup{}

### ISSUE THREAD

**Issue by TristanCrawford** [neovim/nvim-lsp#155]
Possible duplicate of #70

Settings that aren't already in the default configuration are respected, but the others are not.

- `nvim --version`: v0.5.0-414-gfbc4c4fd3
- nvim-lsp version: master
- What language server(If the problem is related to a specific language server): texlab
- Operating system/version: Arch Linux
- Terminal name/version: st
- `$TERM`: st-256color

### How to reproduce the problem from neovim startup
In my init.vim (wrapped in `lua <<`)
```lua
local nvim_lsp = require'nvim_lsp'
nvim_lsp.texlab.setup{
  log_level = vim.lsp.protocol.MessageType.Log;
  message_level = vim.lsp.protocol.MessageType.Log;
  settings = {
    latex = {
      build = {
        args = { '--output-directory=out', '--synctex=1', '--interaction=nonstopmode' },
        executable = 'lualatex',
        onSave = true,
        outputDirectory = './out'
      },
      forwardSearch = {
        args = { '--synctex-forward', '%l:1:%f', '%p' },
        executable = 'zathura'
      },
      lint = {
        onChange = true
      }
    }
  }
}
```

### Actual behaviour
Running `lua print(vim.inspect(vim.lsp.buf_get_clients()))` shows:
```lua
settings = {
  ...
  latex = {
    build = {
      args = { "-pdf", "-interaction=nonstopmode", "-synctex=1" },
      executable = "latexmk",
      onSave = false,
      outputDirectory = "./out"
    },
    forwardSearch = {
      args = {},
      executable = "zathura",
      onSave = false
    },
    lint = {
      onChange = false
    }
  }
}
```
The non-default values are added, but the others remain unchanged.

### Expected behaviour
The settings, such as the `latex.build.executable` should be overridden as specified in the setup call.

**Comment by h-michael** [comment]
@TristanCrawford Can this(#178) solve this issue?
