### ISSUE TITLE
Option for automatically showing signature help when writing the signature

### ISSUE THREAD

**Issue by urandom** [neovim/nvim-lsp#158]
Would it be possible to add a global option that automatically pops up the signature help, preferably only when there is signature help to be shown?

**Comment by h-michael** [comment]
This plugin is only for client config, not for addtional callbacks and operations.

BTW, I write plugin for nvim built-in lsp.
This plugin includes autocmd for signature help.

https://github.com/h-michael/lsp-contrib.nvim

**Comment by urandom** [comment]
@h-michael 

even your plugin does not show signatures without problems. This appears to be a deeper problem, as its the same as when using cursorhold/cursormove. While typing, the signature popup steals "focus" and you end up navigating within the popup itself

**Comment by h-michael** [comment]
@urandom Thanks for the report. Please create an issue in my repository if you like. I'll check it later.
