### ISSUE TITLE
nvim_lsp.pyls.setup{} breaks fugitive functionality

### ISSUE THREAD

**Issue by timfeirg** [neovim/nvim-lsp#161]
- `nvim --version`: v0.5.0-nightly-1640-g2b00d1d09
- nvim-lsp version: 78b16eb3623c1c0d4433ca8e09c2cb661fa1a852
- What language server(If the problem is related to a specific language server): [N/A]
- Operating system/version: Mac OS
- Terminal name/version: Iterm2
- `$TERM`: xterm-256color-italic

### How to reproduce the problem from neovim startup

1. open up neovim using this minimal .nvimrc:

```vimL
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-fugitive'
Plug 'neovim/nvim-lsp'
call plug#end()

lua << EOF
local nvim_lsp = require'nvim_lsp'
nvim_lsp.pyls.setup{
}
EOF
```

2. run `:Gsplit` and expect fugitive to work

### Actual behaviour

fugitive doesn't work, instead, it says:

![image](https://user-images.githubusercontent.com/4319104/75994321-c1599380-5f35-11ea-99f2-8e38b911c511.png)

### Expected behaviour

fugitive should open up a split.

**Comment by timfeirg** [comment]
moreover, if I remove the lua heredoc from my minimal vimrc, the problem is gone.

**Comment by h-michael** [comment]
This is because the buffer name created by fugitive-vim does not actually exist on the file system, so it seems that an error occurs when trying to auto-detect the lsp root directory from that buffer name.

**Comment by timfeirg** [comment]
should I move this issue to fugitive space?

**Comment by h-michael** [comment]
@timfeirg Would you try this branch?
https://github.com/neovim/nvim-lsp/pull/179

**Comment by timfeirg** [comment]
just tried 83da1868b42af72710eef22eb94a89ba42986fe4, `:Gsplit` got a different error this time:

![image](https://user-images.githubusercontent.com/4319104/77280757-2536d700-6d00-11ea-9b95-8986b1089223.png)

**Comment by h-michael** [comment]
@timfeirg oh I'm sorry. log module is not exposed.
I'll create PR to nvim and then it'll work.

**Comment by h-michael** [comment]
@timfeirg I've fixed PR.

**Comment by timfeirg** [comment]
indeed fixed, this is life-saving, thanks!
