### ISSUE TITLE
Rust-analyzer can not be started on current nightly nvim

### ISSUE THREAD

**Issue by matu3ba** [neovim/nvim-lsp#186]
- `nvim --version`: 
NVIM v0.5.0-418-g87d892af
- nvim-lsp version(commit hash): 
d87c037dd309a2de03739bd866bcbf22fc1d838
- `:checkhealth` result 
  - ERROR: rust_analyzer: The given command "rust-analyzer" is not executable.
- What language server(If the problem is related to a specific language server):
  - rust_analyzer
- Operating system/version:
  - Manjaro 19.0.2 (Arch derivative)
- Terminal name/version:
  - Alacritty
- `$TERM`:
  - screen-256color

### How to reproduce the problem from neovim startup
nvim anyFile.rs
### Actual behaviour
Fehler beim Ausführen von "FileType Autokommandos für "rust"":
E5108: Error executing lua ..._nvim.a4YUVeu/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:199: The given command "rust-analyzer" is not executable
### Expected behaviour
rust-analyzer starts and is executable.

Could you also give instructions in the README how too debug the lua code?
Others were failing on trying to do this [here](https://github.com/prabirshrestha/vim-lsp/issues/263) and I would like to help to fix the problem, if there would be any instructions.

**Comment by h-michael** [comment]
@matu3ba Can you execute `rust-analyzer` in your shell?

**Comment by matu3ba** [comment]
The executable for the server from github is called `ra_lsp_server`, but this plugin expects to find `rust-analyzer`.

I tried a solution without renaming the executable provided by the examples:
```
lua << EOF
local nvim_lsp = require'nvim_lsp'
nvim_lsp.rust_analyzer.setup {
  cmd = { "ra_lsp_server" };
}
EOF
```

However this returns
LSP[rust_analyzer] rust-analyzer failed to load workspace: can't load standard library from sysroot
$HOME/.rustup/toolchains/1.39.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src
(discovered via `rustc --print sysroot`)
and then
try running `rustup component add rust-src` or set `RUST_SRC_PATH`

Any advice?

**Comment by h-michael** [comment]
ra_lsp_server is old command name.
It was renamed to rust-analyzer.
So you should install or uodate latest rust-analyzer command.
See https://github.com/neovim/nvim-lsp/pull/128

**Comment by matu3ba** [comment]
Thanks.
