### ISSUE TITLE
configs.lua nil value error when using gopls.setup{} as in README

### ISSUE THREAD

**Issue by doronbehar** [neovim/nvim-lsp#190]
- `nvim --version`: master from 9 hours ago.

```
NVIM v0.5.0-dev
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: 
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/nix/store/1j4bcx8p2d6zr9a6b7qw4lhjlfpp6ha0-neovim-beta-unwrapped-0.5.0/share/nvim
"

Run :checkhealth for more info
```

- nvim-lsp version(commit hash): current master - `b6dc2ae6a95051e93486224481b80cb5b446dcc3`.
- `:checkhealth` result:

```

health#info#check
========================================================================
## info.vim
  - OK: Version 6.5 of standalone info installed.

health#vimtex#check
========================================================================
## vimtex
  - OK: Vim version should have full support!
  - WARNING: bibtex is not executable, so bibtex completions are disabled.
  - OK: General viewer should work properly!
  - ERROR: |g:vimtex_compiler_method| (`latexmk`) is not executable!

health#nvim_lsp#check
========================================================================
## Checking language server protocol configuration
  - INFO: gopls: configuration checked.

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - INFO: Build type: Debug
  - WARNING: Non-optimized (DEBUG) build. Nvim will be slower.
    - ADVICE:
      - Install a different Nvim package, or rebuild with `CMAKE_BUILD_TYPE=RelWithDebInfo`.
      - https://github.com/neovim/neovim/wiki/FAQ

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='rxvt-xpm'

## tmux
  - OK: escape-time: 0ms
  - INFO: $TERM: tmux-256color
  - WARNING: Neither Tc nor RGB capability set. True colors are disabled. |'termguicolors'| won't work properly.
    - ADVICE:
      - Put this in your ~/.tmux.conf and replace XXX by your $TERM outside of tmux:
          set-option -sa terminal-overrides ',XXX:RGB'
      - For older tmux versions use this instead:
          set-option -ga terminal-overrides ',XXX:Tc'

health#provider#check
========================================================================
  - ERROR: Failed to run healthcheck for "provider" plugin. Exception:
    function health#check[21]..health#provider#check[5]..<SNR>237_check_ruby, line 15
    Vim(let):E117: Unknown function: provider#ruby#Detect


```

- What language server(If the problem is related to a specific language server): gopls
- Operating system/version: NixOS
- Terminal name/version: rxvt-unicode + tmux
- `$TERM`: `tmux-256color`

### How to reproduce the problem from neovim startup

I installed gopls with: `go get golang.org/x/tools/gopls@latest` and I have a `gopls` executable in my `$PATH`.

I haven't checked other language servers, but I tried to use gopls with:

```vim
luado require'nvim_lsp'.gopls.setup{}
```

Is there anything wrong with this command?

### Actual behaviour

I'm getting the error:

```
E5111: Error calling lua: ...ig/nvim/pack/functional/opt/lsp.configs/lua/nvim_lsp/configs.lua:72: attempt to index local 'config' (a nil value)
```

EDIT: I get the same error with pyls as well :(.

### Expected behaviour

LSP is running.

**Comment by h-michael** [comment]
@doronbehar 
Does this still occur?
If yes, would you show me  the 10 lines before and after "...ig/nvim/pack/functional/opt/lsp.configs/lua/nvim_lsp/configs.lua"?

**Comment by doronbehar** [comment]
No error anymore, but I don't see any completions triggered... Am I supposed to have it automatically suggested?

**Comment by h-michael** [comment]
@doronbehar See`:h lsp-config`

**Comment by doronbehar** [comment]
> @doronbehar See:h lsp-config

OK, I see there are mappings etc I need to set. I've set them and nothing happens when I press them. There is even no `gopls` process running although I ran:

```vim
luado require'nvim_lsp'.gopls.setup{}
```

**Comment by h-michael** [comment]
Would you show me `:lua print(vim.inspect(vim.lsp.buf_get_clients()))` ?

**Comment by doronbehar** [comment]
`{}`

**Comment by doronbehar** [comment]
@h-michael I appreciate your willing to help but I'm afraid I don't have much time to debug this further. I was just interested in testing Neovim's upcoming native lsp capabilities but since it seems almost unusable at this point, I'll just continue to use `coc.nvim`.

Feel free to close this if you see no issues on your end.

**Comment by h-michael** [comment]
@doronbehar 
I'm sorry that I can't help you. If you use it again and encounter the same problem, please help me again.

**Comment by NeilGirdhar** [comment]
This happens whenever I set any of:
```lua
    vim.g.loaded_node_provider = false
    vim.g.loaded_perl_provider = false
    vim.g.loaded_ruby_provider = false
```
