### ISSUE TITLE
Npm install language server in wrong directory

### ISSUE THREAD

**Issue by theJian** [neovim/nvim-lsp#206]
- nvim-lsp version(commit hash): d16b49e
- What language server(If the problem is related to a specific language server):
  It is related to language servers installed by npm.

### How to reproduce the problem from neovim startup

1. Create a package.json in the home directory.
2. Run :LspInstall \<language-server-installed-by-npm\>

### Actual behaviour

Install failed.
nvim-lsp looks up `.cache/nvim/nvim_lsp/<langserver>` and it is empty.
because npm install it in the home directory.

When running npm install \<package\> without `package.json` in the current directory, npm will try to find it in parent directories. If there is one, npm installs packages in the same directory with where package.json is located in.

https://github.com/neovim/nvim-lsp/blob/d16b49e0ac56e77b81f6192ff4c6f36ee08298e4/lua/nvim_lsp/util.lua#L394-L395

Execute `npm init -y` to create a package.json file before running npm install could solve this issue.

**Comment by theJian** [comment]
There is a proposal to remove installing server #200 . This issue can be automatically resolved if nvim-lsp no longer install server for users.

**Comment by justinmk** [comment]
`:LspInstall` is strictly best-effort. PRs are welcome for improvements but we don't support it. meanwhile covered by https://github.com/neovim/nvim-lsp/issues/200 as you noted.
