### ISSUE TITLE
Usability question: how do you add settings for rust_analyzer?

### ISSUE THREAD

**Issue by nerdrew** [neovim/nvim-lsp#214]
E.g. how can I disable `rust-analyzer.completion.addCallArgumentSnippets`? I've tried these two versions (both are just inline in the settings):

```lua
nvim_lsp.rust_analyzer.setup {
  on_attach = on_attach,
  settings = {
    ["rust-analyzer.completion.addCallArgumentSnippets"] = false;
    ["rust-analyzer"] = {
      completion = {
        addCallArgumentSnippets = false;
      }
    };
  }
}
```

Neither seems to do anything.

Sort of related to https://github.com/rust-analyzer/rust-analyzer/issues/2344

**Comment by h-michael** [comment]
How about this?
```lua
nvim_lsp.rust_analyzer.setup {
  on_attach = on_attach,
  settings = {
    rust-analyzer = {
      completion = {
        addCallArgumentSnippets = false;
      }
    };
  }
}
```

**Comment by lithammer** [comment]
> How about this?
> 
> ```lua
> nvim_lsp.rust_analyzer.setup {
>   on_attach = on_attach,
>   settings = {
>     rust-analyzer = {
>       completion = {
>         addCallArgumentSnippets = false;
>       }
>     };
>   }
> }
> ```

That's not valid Lua. Since there's a dash in `rust-analyzer` it has to be `['rust-analyzer']`.

**Comment by h-michael** [comment]
OK, I'll debug with rust-analyzer tonight.

**Comment by tjdevries** [comment]
@h-michael He's just saying that you need to pt `rust-analyzer` in the Lua way of specifying special strings or items (which is `['rust-analyzer']`). I think your suggestion is good.

**Comment by nerdrew** [comment]
The (fixed) suggestion doesn't seem to be working for me though. I have:

```lua
nvim_lsp.rust_analyzer.setup {
  on_attach = on_attach,
  settings = {
    ["rust-analyzer"] = {
      completion = {
        addCallArgumentSnippets = false;
      }
    };
  }
}
```

which doesn't seem to do anything.

**Comment by nerdrew** [comment]
OOOPS! Sorry. the settings do work as expected. Sorry for the noise! Thanks for the awesome plugin!

This works:

```lua
nvim_lsp.rust_analyzer.setup {
  on_attach = on_attach,
  settings = {
    ["rust-analyzer"] = {
      completion = {
        addCallArgumentSnippets = false,
        addCallParenthesis = false,
      },
    },
  }
}
```

I wasn't correctly using the most recent version of rust-analyzer that supports these settings.
