### ISSUE TITLE
Can the documentation be made clearer on the use of packadd

### ISSUE THREAD

**Issue by TC72** [neovim/nvim-lsp#220]
I recently decided to move from coc.nvim to Neovim's built in LSP. After following the instructions I failed to get it to work. [I started this thread on reddit](https://www.reddit.com/r/neovim/comments/gc775r/please_help_me_understand_neovim_lsp/) and with people's help I've got it working.

It was pointed out to me that the documentation now says many times you must use this line:
`vim.cmd('packadd nvim-lsp')`

After following that and learning how to create a pack directory which allowed me to link my nvim-lsp install to the pack directory I got it working.

If this is the correct way to do this then I think your documentation needs a small improvement as right now it says this:

> Call :packadd nvim-lsp in your vimrc if you installed nvim-lsp to 'packpath' or if you use a package manager such as minpac.

If we must use the packadd method then it should not say "if you installed nvim-lsp to 'packpath'", this gives the impression it's not necessary to do that. As it sounded as if it wasn't required I ignored every instruction to use packadd. Some kind of help to explain how to install it to packpath would also be good.

You might be able to see from reddit that someone is now commenting that I'm completely wrong and packadd isn't needed, but if I remove it I can't get the built in LSP to work.
If I've got this completely wrong and I need to do something else to get it working please let me know.

Thanks for your hard work, much happier using built in LSP with vim-mucomplete than using coc.nvim that I didn't have a clue how to control what it was doing.

**Comment by justinmk** [comment]
> the documentation now says many times you must use this line:
> `vim.cmd('packadd nvim-lsp')`
> 
> After following that and learning how to create a pack directory which allowed me to link my nvim-lsp install to the pack directory I got it working.

The `vim.cmd('packadd nvim-lsp')` line in the doc is confusing, yes, specially if you're not familiar with Vim. It is assumed that you would only add that line if you actually use 'packpath'.

The problem is some package managers use 'packpath', some don't. vim-plug does not.

> Some kind of help to explain how to install it to packpath would also be good.

Depends on your package manager. The fact that you had to _create_ a 'packpath' directory means your package manager doesn't use 'packpath'... otherwise it would have created the directory for you.

> someone is now commenting that I'm completely wrong and packadd isn't needed, but if I remove it I can't get the built in LSP to work.

Need more details than that...

**Comment by TC72** [comment]
I'm using this to install the plugin:
`Plug 'neovim/nvim-lsp'`

If I don't use the `vim.cmd('packadd nvim-l` then I get this error message on launch:

`Error detected while processing /Users/julianf/Dropbox/dotfiles/vim/my_config/nvim-lsp.vim:
line   17:
E5108: Error executing lua [string ":lua"]:1: module 'nvim_lsp' not found:
        no field package.preload['nvim_lsp']
        no file '/Users/julianf/.config/nvim/lua/nvim_lsp.lua'
        no file '/Users/julianf/.config/nvim/lua/nvim_lsp/init.lua'`

and the list keeps going on.

**Comment by justinmk** [comment]
and what directory did you tell vim-plug to install to...?

The error message tells us it's looking in `.config/nvim/...`. Clearly vim-plug is installing somewhere else.

**Comment by TC72** [comment]
I don't know, I've always just used a line like `Plug 'tpope/vim-repeat'` in my init.vim and plugins work. Never configured it to say which directory to use.
I can see the plugins are installed in ~/.config/nvim/bundle/

**Comment by justinmk** [comment]
are other plugins being found? what does this say:

    :put =&runtimepath

**Comment by justinmk** [comment]
Actually, the problem might be that you're calling `require'nvim_lsp'` before calling `plug#end()`. Can you try putting the Lua code somewhere after `plug#end()`

**Comment by TC72** [comment]
Yes, that was the problem, I moved it after plug#end() and it works.
Thanks for taking the time to help me. I'll update the reddit post in case it can help anyone else.

**Comment by gobwas** [comment]
@justinmk also the question is, why should I call `packadd nvim-lspconfig` if I put plugin contents under `~/.local/share/nvim/site/pack/plugin/start/nvim-lspconfig/plugin/nvim_lsp.vim`, which means that due to **start** directory neovim would load it during startup (and neovim actually loads it as `:scriptnames` points out). 

But still, if I don't call `packadd`, I can't import nvim_lsp lua module...
