### ISSUE TITLE
Configuring elixir ls

### ISSUE THREAD

**Issue by skbolton** [neovim/nvim-lsp#230]
- `nvim --version`: v0.5.0-nightly
- nvim-lsp version(commit hash): b77a24f
- `:checkhealth` result
```

health#nvim_lsp#check
========================================================================
## Checking language server protocol configuration
 - INFO: elixirls: configuration checked.

health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript bundle found
  - OK: Service started

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 1ms
  - INFO: $TERM: tmux-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy
```
- What language server(If the problem is related to a specific language server): elixir ls (new one I will PR if I can get working)
- Operating system/version: MacOS Catalina 10.15.4
- Terminal name/version: Kitty
- `$TERM`: xterm-256color

I was working on trying to tackle adding support for [elixir-ls](https://github.com/elixir-lsp/elixir-ls) to this project, but I was having a hard time diagnosing issues. When I open an elixir buffer and run `:lua print(vim.inspect(vim.lsp.buf_get_clients()))` I get output of the server being attached. After 10 seconds or so (or sending any lsp command) the language server crashes. When viewing the log file found at `:lua print(vim.lsp.get_log_path())` there is nothing but blank lines. It seems that the only time I can get an error to show up is when I open a buffer and quickly send a lsp command (hover) before the timeout. The error in the file is straight from elixir ls and basically just says that the server is not running.

Here is the configuration I have tried to use so far in my `init.vim`:
```
:lua << END
  vim.cmd('packadd nvim-lsp')  -- If installed as a Vim "package".
  local nvim_lsp = require'nvim_lsp'
  local configs = require'nvim_lsp/configs'
  configs.elixirls = {
    default_config = {
      cmd = {'/Users/stephenbolton/Development/elixir-ls/rel/language_server.sh'};
      filetypes = {'elixir', 'eelixir'};
      root_dir = nvim_lsp.util.root_pattern("mix.exs", ".git");
      settings = {};
      log_level = 0;
    };
  }
  nvim_lsp.elixirls.setup{}
END
```

I have been working with this same language server for a few months now in `coc`. For reference here is its config in `coc`:
```
...
    "elixirLS": {
      "command": "~/Development/elixir-ls/rel/language_server.sh",
      "filetypes": ["elixir", "eelixir"],
      "settings": {}
    },
...
```

Also if it is helpful I have turned on tracing and ran `:CocInfo` on a file when using `coc`. This gist shows the output:  https://gist.github.com/skbolton/295ec6305b91c86d43812254c85d2f54
> In this gist I am viewing the language server source code with the language server. It is the only elixir I have handy that isn't work stuff.

Let me know if there is anything else I can provide. Sorry if I left important details out. I am still getting the hang of lua and using it in neovim.

**Comment by heimann** [comment]
Have you tried installing elixir-ls into another directory just to be sure that it's not that particularly version of `elixir-ls` that's giving you trouble?

I'm able to get the language-server to run fine, and it doesn't seem to crash on me, but I can't get go to definition to work right just yet :joy:

**Comment by h-michael** [comment]
#243 resolved this
