### ISSUE TITLE
2 display issues with nvim-lsp and rust-analyzer

### ISSUE THREAD

**Issue by sbromberger** [neovim/nvim-lsp#252]
- `nvim --version`: `NVIM v0.5.0-504-g55b62a937`
- `:checkhealth` result: all ok except for missing providers: py2, ruby, node, and perl
- What language server(If the problem is related to a specific language server): rust-analyzer
- Operating system/version: Ubuntu 20.04
- Terminal name/version `$TERM`: `tmux-256color-italic`

Additional info:
```
let g:LspDiagnosticsErrorSign = ''                                                                                                             
let g:LspDiagnosticsWarningSign = ''
```
(These are unicode chars)

### How to reproduce the problem from neovim startup
issue 1: start nvim, note that errors are displayed with default(?) markings instead of overridden by `LspDiagnosticsErrorSign` for rust only.

issue 2: after removing an error, the statusbar changes (note strange highlighted block at right of statusbar).

### Actual behaviour

Video here: https://asciinema.org/a/k8RDPOZv8anMdIeYFa8UEVvgF

### Expected behaviour
1) expect custom symbols in gutter for rust-analyzer
2) expect statusbar to be consistent

**Comment by tjdevries** [comment]
Help defines new way to set these:

```
sign define LspDiagnosticsErrorSign text=E texthl=LspDiagnosticsError linehl= numhl=
sign define LspDiagnosticsWarningSign text=W texthl=LspDiagnosticsWarning linehl= numhl=
sign define LspDiagnosticsInformationSign text=I texthl=LspDiagnosticsInformation linehl= numhl=
sign define LspDiagnosticsHintSign text=H texthl=LspDiagnosticsHint linehl= numhl=
```

**Comment by sbromberger** [comment]
Issue 1 is because of the syntax change for the gutter signs:
```
sign define LspDiagnosticsErrorSign text=E texthl=LspDiagnosticsError linehl= numhl=
sign define LspDiagnosticsWarningSign text=W texthl=LspDiagnosticsWarning linehl= numhl=
sign define LspDiagnosticsInformationSign text=I texthl=LspDiagnosticsInformation linehl= numhl=
sign define LspDiagnosticsHintSign text=H texthl=LspDiagnosticsHint linehl= numhl=
```
fixed it.

Still having problems with issue 2.

**Comment by sbromberger** [comment]
@tjdevries could you please reopen? Still having issues with 2.

**Comment by h-michael** [comment]
@sbromberger 
This reproduced video seems to have plugins and settings other than nvim-lsp.
Please tell me the minimum reproduction vimrc.

**Comment by sbromberger** [comment]
@h-michael see https://github.com/rust-analyzer/rust-analyzer/issues/4630#issuecomment-636463332 - according to the logs, nvim-lsp is not sending the `\n` from the penultimate line.
