### ISSUE TITLE
nvim-lsp not sending full code to rust-analyzer

### ISSUE THREAD

**Issue by sbromberger** [neovim/nvim-lsp#256]
- `nvim --version`: `NVIM v0.5.0-532-g2ca8f02a6`
- `:checkhealth` result: all good except for missing providers
- What language server(If the problem is related to a specific language server): rust-analyzer
- Operating system/version: Ubuntu 20.04
- Terminal name/version: blink app, via mosh
- `$TERM`: tmux-256color-italic

### How to reproduce the problem from neovim startup
1) create a simple rust file after `cargo init --bin`: https://gist.github.com/f796385f05096c17 and save it
2) using rust analyzer config:
```
lua << EOF
  local nvim_lsp = require'nvim_lsp'
  local on_attach = function(_, bufnr)
    vim.api.nvim_buf_set_option(bufnr, 'omnifunc', 'v:lua.vim.lsp.omnifunc')
    require'diagnostic'.on_attach()
    require'completion'.on_attach()
  end
  nvim_lsp.rust_analyzer.setup{
    on_attach=on_attach;
  }
EOF
```
edit the file. hit `:w` to write the file.
### Actual behaviour
Spurious error complaining about missing right curly brace.

### Expected behaviour
No error.

Video demonstration of error: https://asciinema.org/a/O97Y5icC8HfdETZ37CWgZzURv

LSP log trace: https://gist.github.com/sbromberger/909ce6d5723bb0d0d8b9e3e7424efaec

Related issue: https://github.com/rust-analyzer/rust-analyzer/issues/4630

**Comment by tjdevries** [comment]
Can you make this issue on `neovim` not `nvim-lsp` please? This is not the right repo for this issue (this is primarily for configs, not for core language server issues). When you do, can you close this issue?

**Comment by sbromberger** [comment]
@tjdevries ref https://github.com/neovim/neovim/issues/12414. Sorry for the mispost.

**Comment by tjdevries** [comment]
No problem :) thanks for posting there.
