### ISSUE TITLE
vimls omnifunc  attempt to compare nil with string

### ISSUE THREAD

**Issue by nhooyr** [neovim/nvim-lsp#261]
- `nvim --version`: `NVIM v0.5.0-60c581b`
- nvim-lsp version(commit hash): a7fdf268b1c51f6395900e437060728701aa8b77
- `:checkhealth` result
```
## Checking language server protocol configuration
  - INFO: vimls: configuration checked.
  - INFO: gopls: configuration checked.
  - INFO: tsserver: configuration checked.
```
- Operating system/version: macOS 10.15.5
- Terminal name/version: Terminal.app
- `$TERM`: xterm-256color

### How to reproduce the problem from neovim startup

Just `<C-x><C-o>` after installing vimls in a vim file.

Throws:

```
Error executing vim.schedule lua callback: ...vim/HEAD-60c581b/share/nvim/runtime/lua/vim/lsp/util.lua:267: attempt to compare nil with string
```

**Comment by tjdevries** [comment]
This should probably be an issue on `neovim` I'm assuming (since this is just for the configs)

**Comment by nhooyr** [comment]
You got it. I wasn't sure as someone on gitter redirected me to file any lsp related issues here.

**Comment by nhooyr** [comment]
See https://github.com/neovim/neovim/issues/12431
