### ISSUE TITLE
Slow responce from the pyls

### ISSUE THREAD

**Issue by nacknime-official** [neovim/nvim-lsp#271]
- `nvim --version`:
```
NVIM v0.5.0-547-gdd4018947Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-410d26af-e3fc-46f1-9ea4-44eef6b04ebd

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"Run :checkhealth for more info
```
- nvim-lsp version(commit hash): 94cce74
- `:checkhealth` result
```

health#nvim_lsp#check
========================================================================
## Checking language server protocol configuration
  - INFO: pyls: configuration checked.

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: wl-copy

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /home/pro/.local/share/virtualenvs/gdz_ukraine-9Hy83Z4E/bin/python is Python 3.8 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/bin/python3"
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.8.3
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: $VIRTUAL_ENV provides :python, :python3, et al.

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v14.3.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

## Perl provider (optional)
  - WARNING: `perl` and `cpanm` must be in $PATH.
    - ADVICE:
      - Install Perl and cpanminus and verify that `perl` and `cpanm` commands work.
```
- What language server(If the problem is related to a specific language server): `pyls`
- Operating system/version: `Archlinux + Sway (walyand)`
- Terminal name/version: `kitty 0.17.4`
- `$TERM`: `xterm-256color`

### How to reproduce the problem from neovim startup
With the minimal nvim config
```
call plug#begin('~/.vim/plugged') 
    Plug 'neovim/nvim-lsp'
call plug#end()
lua require'nvim_lsp'.pyls.setup{}
au Filetype python setl omnifunc=v:lua.vim.lsp.omnifunc

set completeopt=menuone,noinsert,noselect
let g:python3_host_prog = '/usr/bin/python3'
```
I press `<C-x><C-o>` to call the completion menu after `await message.` to get `message's` methods (not only in aiogram, different modules needs to wait different time)

### Actual behaviour
Suggestions shows very slow comparing with [Coc.nvim](https://github.com/neoclide/coc.nvim) + [Coc-python](https://github.com/neoclide/coc-python), Jedi is enabled
Nvim-lsp
![slow_completion_nvim](https://user-images.githubusercontent.com/34421603/84437949-83f45880-ac3e-11ea-89bc-a72beda6205f.gif)
Coc.nvim + Coc-python
![slow_completion_nvim_coc](https://user-images.githubusercontent.com/34421603/84437990-95d5fb80-ac3e-11ea-9fe5-7f26dc020d18.gif)

### Expected behaviour
Faster responce like in coc.nvim + coc-python

I don't know this issue of nvim-lsp or pyls, but coc.nvim works through jedi or pyls and works faster than nvim-lsp, correct me if I'm wrong

**Comment by mjlbach** [comment]
Just to clarify, VScode does not use palantir's python language server, but rather a custom implementation on top of [jedi](https://github.com/microsoft/vscode-python/blob/f1f2dfd192358a0c9641a6af7d81fb1dee217ea5/pythonFiles/completion.py). I've also noticed slow completions from pyls when using vim-lsp/LanguageClient-neovim. You should try using mspyls (the Microsoft Python Language Server), which I added to nvim-lsp, and is *much* faster.

**Comment by nacknime-official** [comment]
> Just to clarify, VScode does not use palantir's python language server, but rather a custom implementation on top of [jedi](https://github.com/microsoft/vscode-python/blob/f1f2dfd192358a0c9641a6af7d81fb1dee217ea5/pythonFiles/completion.py). I've also noticed slow completions from pyls when using vim-lsp/LanguageClient-neovim. You should try using mspyls (the Microsoft Python Language Server), which I added to nvim-lsp, and is _much_ faster.

I haven't say that I compared with VSCode, I compared with coc.nvim, these things are different.

What about pyls_ms - that's laggy, buggy and eats too much CPU since open a python file.

**Comment by mjlbach** [comment]
> I haven't say that I compared with VSCode, I compared with coc.nvim, these things are different.

coc-python is a [fork](https://github.com/neoclide/coc-python/blob/master/Readme.md) of VSCode's python plugin. 

>What about pyls_ms - that's laggy, buggy and eats too much CPU since open a python file.

pyls_ms is the same language server that coc-python uses when you disable jedi in coc-settings.json. It's significantly faster in my experience for most projects.

**Comment by nacknime-official** [comment]
> > I haven't say that I compared with VSCode, I compared with coc.nvim, these things are different.
> 
> coc-python is a [fork](https://github.com/neoclide/coc-python/blob/master/Readme.md) of VSCode's python plugin.
> 
> > What about pyls_ms - that's laggy, buggy and eats too much CPU since open a python file.
> 
> pyls_ms is the same language server that coc-python uses when you disable jedi in coc-settings.json. It's significantly faster in my experience for most projects.

yes, it's faster, but we're talking about pyls now. On my screencasts you can see that jedi in coc.nvim (I didn't disable jedi in the coc config file) is much faster than in nvim-lsp

**Comment by mjlbach** [comment]
You can't compare the speed of pyls in nvim-lsp, to the speed of pyls in coc-python, because coc-python does *not* use pyls. Pyls is the speed bottleneck, not the nvim lsp implementation. To confirm, you can try LanguageClient-neovim and vimls, they will both have the same delay. 

What you're really asking for is a feature request, to make a new language server using the jedi implementation of vscode (which coc-python forked/wraps), and then to provide support for that in nvim-lsp. Microsoft isn't really developing that anymore in favor of the new C# based mspyls, which we already deliver.

**Comment by fsouza** [comment]
@nacknime-official as mentioned by @mjlbach, coc-python doesn't use pyls, it uses jedi directly. If you want to compare the speed, you can configure coc.nvim to use pyls by uninstalling coc-python and following these instructions: https://github.com/neoclide/coc.nvim/wiki/Language-servers#python (spoiler alert: it'll be as slow, because pyls is the problem here).

This should be an issue in python-language-server's issue tracker.

**Comment by nacknime-official** [comment]
Oh, I'm so sorry, I thought coc-python uses pyls. Thanks for you all, I'm closing this issue.

**Comment by Shougo** [comment]
If nvim-lsp supports https://github.com/pappasam/jedi-language-server, it may solve the problem instead.

**Comment by fsouza** [comment]
Oh interesting, sent #284.
