### ISSUE TITLE
Bug: Leaking child processes

### ISSUE THREAD

**Issue by ms-jpq** [neovim/nvim-lsp#278]
- `nvim --version`:

NVIM v0.5.0-2ca8f02

- nvim-lsp version(commit hash):

1de73d2bd7878b9232ec784cc076f06e99c9b27d

- `:checkhealth` result

Doesn't seem to work?

```
health#nvim_lsp#check
========================================================================
## Checking language server protocol configuration
```

- What language server(If the problem is related to a specific language server):

`pyls_ms` and the lua one

- Operating system/version:

```
 Darwin Kernel Version 19.5.0:
```

- Terminal name/version:
iTerm2

- `$TERM`:

`screen-256color`

### How to reproduce the problem from neovim startup

Start Neovim, edit some lua / python files, exit.

The LSP child process remains alive after Neovim exits.

### Actual behaviour
<img width="1417" alt="图片" src="https://user-images.githubusercontent.com/50598611/84588204-2dbc1c80-adda-11ea-962d-83213fae2592.png">

### Expected behaviour

No child left behind.

**Comment by norcalli** [comment]
It very much depends on how the process is being started, how nvim is being exited, and how the lua-language-server handles signals.

On exit, the built-in lsp send

**Comment by ms-jpq** [comment]
thanks foe the explanation!
