### ISSUE TITLE
Using document_range_formatting with formatexpr

### ISSUE THREAD

**Issue by meck** [neovim/nvim-lsp#288]
Testing the builtin Lsp, loving it so far! I hit a minor issue while configuring everything.
I wanted to use Lsp formatting with `formatexpr`,  however setting:
`api.nvim_buf_set_option(bufnr, 'formatexpr', 'v:lua.vim.lsp.buf.range_formatting()')`
has some issues as `formatexpr` expects to use the range in `v:lnum` `v:count` and
only works on whole lines.

I managed to solve it by wrapping the call (I don't know any Lua so this this is most likely terrible):
```lua
Formatexpr_wrapper = function()
 -- only reformat on explicit gq command
 if not fn.mode() == 'n' then
    -- fall back to Vims internal reformatting
    return 1
 end

 local opts = {}
 local start_line = vim.v.lnum
 local end_line = start_line + vim.v.count - 1
 if start_line >= 0 and end_line >= 0 then
   lsp.buf.range_formatting(opts, {start_line, 0}, {end_line, 0})
 end

 return 0
end
```

I was thinking functionality like this might be good to include in this plugin?

**Comment by tjdevries** [comment]
Oh, this is a good idea! Can you submit it to the neovim core repo? And then tag me (@tjdevries) in it?

**Comment by tjdevries** [comment]
Closing since this issue is better suited for core. Thanks @meck
