### ISSUE TITLE
Plan to support Deno in this project?

### ISSUE THREAD

**Issue by nabezokodaikon** [neovim/nvim-lsp#311]
Plan to support [Deno](https://deno.land/) in this project?
It seems that VSCode and coc.nvim are compatible.

**Comment by nabezokodaikon** [comment]
It has the same extension as the conventional TypeScript, and it seems difficult to distinguish it.

**Comment by Shougo** [comment]
It uses LSP protocol?

**Comment by nabezokodaikon** [comment]
Some are published in a form that extends the LSP of TypeSctipr.
[typescript-deno-plugin](https://github.com/justjavac/typescript-deno-plugin/tree/master/typescript-deno-plugin)

**Comment by nabezokodaikon** [comment]
After installing typescript-deno-plugin, if you create tsconfig.json in the project directory, it seems that you can handle it.

tsconfig.json
```json
{
  "compilerOptions": {
    "plugins": [
      {
        "name": "typescript-deno-plugin"
      }
    ]
  }
}
```

```json
.
└── official
    ├── First-steps
    │   └── 02.03
    │       └── example_001.ts
    └── tsconfig.json

```

**Comment by Shougo** [comment]
If so, you can configure it.

**Comment by nabezokodaikon** [comment]
Is it not necessary...?

**Comment by Shougo** [comment]
nvim-lsp is just default configuration for LSP servers.
You can configure any LSP servers without it.
If you can configure, you can create the PR for it.

**Comment by nabezokodaikon** [comment]
I tried using the TypeScript file as a reference. However, I couldn't because I couldn't install the package.
It works with `npm install -g typescript-deno-plugin` for the time being, so I'll use it.
