### ISSUE TITLE
Custom binary

### ISSUE THREAD

**Issue by p00f** [neovim/nvim-lsp#315]
I've installed bash and vim language servers through the archlinux repos and the AUR respectively, their respective launch commands are `bash-language-server` and `vim-language-server`. 
 But `:LspInstallInfo` gives this
```
{
  bashls = {
    bin_dir = "/home/chinmay/.cache/nvim/nvim_lsp/bashls/node_modules/.bin",
    binaries = {
      ["bash-language-server"] = "/home/chinmay/.cache/nvim/nvim_lsp/bashls/node_modules/.bin/bash-language-server"
    },
    install_dir = "/home/chinmay/.cache/nvim/nvim_lsp/bashls",
    is_installed = false
  },
  jdtls = {
    install_dir = "/home/chinmay/.cache/nvim/nvim_lsp/jdtls",
    is_installed = true
  },
  vimls = {
    bin_dir = "/home/chinmay/.cache/nvim/nvim_lsp/vimls/node_modules/.bin",
    binaries = {
      ["vim-language-server"] = "/home/chinmay/.cache/nvim/nvim_lsp/vimls/node_modules/.bin/vim-language-server"
    },
    install_dir = "/home/chinmay/.cache/nvim/nvim_lsp/vimls",
    is_installed = false
  }
}
Press ENTER or type command to continue
```

How can I fix this?

**Comment by lithammer** [comment]
It likely works as expected. I think `is_installed` just means it's not installed via the `:LspInstall` command. I manually install all my language servers and my `:LspInstallInfo` looks similar to yours and everything works just fine.

**Comment by lithammer** [comment]
And I wouldn't worry about the `install_dir`/`bin_dir` values either.

**Comment by p00f** [comment]
They do work as expected,
