### ISSUE TITLE
Obtaining debug information from clangd not possible

### ISSUE THREAD

**Issue by matu3ba** [neovim/nvim-lsp#316]
clangd offers an option to [export logfiles(section vim)](https://clangd.llvm.org/installation.html).
I am in the [process to get better documentation](https://github.com/clangd/clangd/issues/482).
[YouCompleteMe](https://github.com/ycm-core/YouCompleteMe) is suggested and [this file](https://github.com/ycm-core/ycmd/blob/master/ycmd/completers/cpp/clangd_completer.py) should be used.

- `nvim --version`: NVIM v0.5.0-619-g1153ac903
- nvim-lsp version(commit hash): 3f7223659f39273c5fe4f2f2d7ee8baa827a9cfb
- `:checkhealth` result all fine
- What language server(If the problem is related to a specific language server): clangd
- Operating system/version: Manjaro (Arch derivate)
- Terminal name/version: alacritty 0.4.3
- `$TERM`: screen-256color

### How to reproduce the problem from neovim startup
Starting neovim with a `.h` or `.cpp` file cant find file paths. Without logs its unconvenient to fix.

### Actual behaviour
Trying to set `-log=verbose` for `clangd` not possible, since there is no option.
### Expected behaviour
A log file is written.

**Comment by erw7** [comment]
The following settings allow you to do what you want.

```vim
 lua require'nvim_lsp'.clangd.setup{
      \  cmd = {
      \    'clangd',
      \    '--background-index',
      \    '--log=verbose'
      \  },
      \ }
```
