### ISSUE TITLE
Disabling highlights and use underline

### ISSUE THREAD

**Issue by tkolleh** [neovim/nvim-lsp#324]
If possible, how could I change the highlight behavior to not highlight errors nor warnings? I prefer to have them underlined to avoid visual noise.

The following is an image of my Nvim setup. The [Ale plugin](https://github.com/dense-analysis/ale) is enabled with highlights disabled/hidden i.e:

```
let g:ale_disable_lsp = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = ''
let g:ale_sign_warning = ''
let g:ale_set_highlights = 0

highlight clear ALEErrorSign
highlight clear ALEWarningSign
```

<img width="838" alt="Screen Shot 2020-08-23 at 1 11 55 PM" src="https://user-images.githubusercontent.com/3095197/90984510-69decc80-e543-11ea-9a01-354c608408cb.png">

The error is due to a multi-line string, yet to be commented. I'd like for everything to remain the same except for colored highlights to become colored underline. 

> Apologies in advance if this is the wrong forum for such a question.

**Comment by PatOConnor43** [comment]
Are you using [diagnostic-nvim](https://github.com/nvim-lua/diagnostic-nvim)? If you are, this setting controls virtual text https://github.com/nvim-lua/diagnostic-nvim#enabledisable-virtual-text . It looks like diagnostic-nvim also has a setting to use underlines. It should be on by default. https://github.com/nvim-lua/diagnostic-nvim#enabledisable-underline .

If you're using ale on it's own I don't see a way to disable virtual text. (That might be a good issue over there.) Potentially you could make this [time delay](https://github.com/dense-analysis/ale/blob/9e95032b305edf883ae19e848f5a9f27b09a37f1/autoload/ale/virtualtext.vim#L7) really large though as a workaround.

**Comment by tkolleh** [comment]
I am using diagnostic-nvim. The below image was taken using the following settings:

```vim
" Diagnostic nvim configurations
let g:diagnostic_enable_virtual_text = 1
let g:diagnostic_virtual_text_prefix = ''
let g:diagnostic_trimmed_virtual_text = '20'
let g:diagnostic_sign_priority = 20
let g:diagnostic_enable_underline = 0
let g:diagnostic_insert_delay = 1 " Dont show diagnostics while in insert mode
```

<img width="856" alt="Screen Shot 2020-08-23 at 11 21 32 PM" src="https://user-images.githubusercontent.com/3095197/91000556-6a08b780-e597-11ea-9f22-09beacdb349c.png">

Note the `ALEDisable` command was ran prior to creating `some_fn`. I was in insert mode while testing with `some_fn` the `g:diagnostic_insert_delay = 1` prevented the virtual text from displaying but not the highlighting.

**Comment by tkolleh** [comment]
Found the culprit. nvim-treesitter plugin was [highlighting text while I was typing](https://github.com/nvim-treesitter/nvim-treesitter#while-typing-my-code-is-marked-as-red). Adding `highlight link TSError Normal` fixed the mentioned issue.
