### ISSUE TITLE
Internal private language server at work

### ISSUE THREAD

**Issue by dbalatero** [neovim/nvim-lsp#41]
Hi, I have a language server that is private and internal at work, and not open-source.

Is there a straightforward way I can create a definition in my private files and load it into `nvim-lsp` all the same, so I don't have to contribute to this repo and leak internal information? Thanks!

**Comment by norcalli** [comment]
Yes indeed, you can. I do this for testing my own implementations before adding them:

```lua
local nvim_lsp = require'nvim_lsp'
local skeleton = require'nvim_lsp/skeleton'
-- Check if it's already defined for when I reload this file.
if not nvim_lsp.lua_lsp then
  skeleton.lua_lsp = {
    default_config = {
      cmd = {'/home/ashkan/works/3rd/lua-language-server/run.sh'};
      filetypes = {'lua'};
      root_dir = function(fname)
        return nvim_lsp.util.find_git_ancestor(fname) or vim.loop.os_homedir()
      end;
      log_level = vim.lsp.protocol.MessageType.Warning;
      settings = {};
    };
  }
end

nvim_lsp.lua_lsp.setup {
  on_attach = language_client_setup;
}
```

Basically, just require `nvim_lsp/skeleton` and do the same as we do if we were adding it to the repository itself.

Note that adding the definition to the skeleton and doing `.setup()` are two different steps.

**Comment by dbalatero** [comment]
Thank you!!

**Comment by mikker** [comment]
How would this look in vimscript?

**Comment by justinmk** [comment]
@mikker The same. Lua is easy to use from Vimscript. See `:help lua-heredoc`.
