### ISSUE TITLE
Switch root patterns to `or os_homedir()` by default?

### ISSUE THREAD

**Issue by norcalli** [neovim/nvim-lsp#44]
I realized something from some recent PRs, which is that if you want to allow a Language Server for single files not in a project, we can just return homedir, and use the root_pattern/existing mechanism for everything else.

Basically, we should probably do this for most/all servers:

```lua
root_dir = function(fname)
  return nvim_lsp.util.find_git_ancestor(fname) or vim.loop.os_homedir()
end;
```

Where single files will use the homedir instance of the client.

**Comment by st3fan** [comment]
I am not sure if this is a good alternative default. What if the language server starts scanning the whole contents of your home directory recursively?

**Comment by mjlbach** [comment]
I think this is an issue with the microsoft python language server, I'm currently using nvim_lsp.util.find_git_ancestor(fname) or vim.loop.os_homedir() which fails if the file isn't in a git repo

**Comment by justinmk** [comment]
@mjlbach you can set `root_dir` as needed though, right? Or what are you suggesting?

**Comment by mjlbach** [comment]
Yes. Just giving an example of a language server that this doesn't work for as a default

**Comment by justinmk** [comment]
> but it currently silently fails if the language server is started in folder that is not a repo (if os.homedir() is set instead as root_dir)

Ok, we definitely don't want silent failures. That's the most frustrating part of any LSP client :)

**Comment by norcalli** [comment]
Ok so we can evaluate this on an LSP by LSP basis. Some languages are more commonly used for one-off files, and so it can be assumed those LSPs are better equipped to handle the default. We'll conservatively add it if it can be demonstrated to be useful and leave this issue for something to point to to explain how to handle files which are not "in a root_pattern".

**Comment by justinmk** [comment]
Closing since it seems like we decided against, based on above discussion.
