### ISSUE TITLE
Microsoft Python Language Server 

### ISSUE THREAD

**Issue by ahmedelgabri** [neovim/nvim-lsp#55]
Will be great if https://github.com/microsoft/python-language-server is also supported

**Comment by mjlbach** [comment]
I tried working on this, I could get the server to start from the skeleton, but was failing to get any diagnostics/completion.

Here are some relevant implementations:
* emacs: [lsp-python-ms](https://github.com/emacs-lsp/lsp-python-ms/blob/master/lsp-python-ms.el)
* vim [coc-python](https://github.com/neoclide/coc-python) which wraps a fork of the vscode python plugin
* sublime [official mpls repo](https://github.com/microsoft/python-language-server/blob/master/Using_in_sublime_text.md)

If you want to get the nupkg for the mpls, which can be extracted and run with dotnet
```
curl -LO https://pvsc.azureedge.net/python-language-server-stable/Python-Language-Server-linux-x64.0.4.58.nupkg
```

**Comment by mjlbach** [comment]
See #57
