### ISSUE TITLE
Reason Language Server

### ISSUE THREAD

**Issue by peterpme** [neovim/nvim-lsp#6]
Hey there,

I'd like to get [Reason](https://reasonml.github.io/) language server in here as well - are there steps I should follow besides looking at the current PR?

https://github.com/jaredly/reason-language-server

Thanks!

**Comment by norcalli** [comment]
If you have experience with the LSP, then use your best judgement to come up with defaults for the LSP.

Things to consider:

- root_dir pattern
- available settings for configuration
- offset_encoding
- commands to add support for
- Installation instructions or usage notes

For all of those things, there's an existing server which can be looked at for an example of how you could do it, so look at the existing PR and the other servers under nvim_lsp and give it a shot. It's made to be easy even if you don't necessarily know Lua.

**Comment by justinmk** [comment]
Send a PR. See other PRs for examples.
