### ISSUE TITLE
Permission denied issues while using gopls

### ISSUE THREAD

**Issue by suessflorian** [neovim/nvim-lsp#60]
I'm having issues going to definition (`vim.lsp.buf.definition()`) while inside go mod installed packages.

```
LSP[gopls] 2019/12/03 20:35:25 no CheckPackageHandles: go [list -f {{context.GOARCH}} {{context.Compiler}} -- unsafe]: exit status 1: error writing go.mod: open /Users/florians
uess/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/go.mod298498081.tmp: permission denied
Press ENTER or type command to continue
^IURI = file:///Users/floriansuess/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/exported.go
Press ENTER or type command to continue
```

Note; these issues completely resolve themselves when nvim is fired in sudo.

**Comment by justinmk** [comment]
source code is here: https://github.com/neovim/nvim-lsp/blob/master/lua/nvim_lsp/gopls.lua

We don't support every system/configuration/environment, we just provide best-effort configs to get started. PR welcome if you find a problem.
