### ISSUE TITLE
error while calling lua chunk attempt to index upvalue 'uv' ( a nil value ) at startup

### ISSUE THREAD

**Issue by D-K-E** [neovim/nvim-lsp#65]
After installing nvim-lsp with dein plugin manager. I get the following error on the startup of neovim:
```
E5105: Error while calling lua chunk: .../.cache/dein/.cache/init.vim/.dein/lua/nvim_lsp/util.lua:121: attempt to index upvalue 'uv' (a nil value)
```

Here is neovim info:
```
NVIM v0.3.2-649-g512e0ca
Build type: Debug
LuaJIT 2.0.5
```

**Comment by norcalli** [comment]
Oh yeah you're using a way older version than is supported. This requires master. As in as yet unreleased. You can grab the appimage from neovim.io or build it yourself.

**Comment by ephemerr** [comment]
I am on Ubuntu 18.04 and have same error with default nvim package. Then I've used appimage from neovim.io and have other error: 
`~/.vim/bundle/nvim-lsp/lua/nvim_lsp/util.lua:315: attempt to index local 'fn' (a nil value)`

nvim-lsp from master branch

**Comment by norcalli** [comment]
@ephemerr create a new issue.

**Comment by ephemerr** [comment]
nvim-lsp require nightly build nvim now.
If you want to use, you build nvim master branch or wait for nvim v0.5.0.

_Originally posted by @h-michael in https://github.com/neovim/nvim-lsp/issues/81#issuecomment-568889095_

so appimage is not solution

**Comment by norcalli** [comment]
@ephemerr ah I see now. I assumed there was an appimage for nightly. Yes that's correct. Try to obtain a copy of nightly neovim.

**Comment by justinmk** [comment]
> I assumed there was an appimage for nightly.

There is: https://github.com/neovim/neovim/releases/tag/nightly
