### ISSUE TITLE
Vim LSP, is it worth it?

### ISSUE THREAD

**Issue by ahmedelgabri** [neovim/nvim-lsp#66]
Is it worth adding a `vim-lsp` that's written in JavaScript like https://github.com/iamcco/vim-language-server or there are any plans to have this natively for example?

**Comment by norcalli** [comment]
Maybe but I think we should steal that signaturehelp style for the core lsp. I really should improve that feature.

**Comment by ahmedelgabri** [comment]
True & that's also one more reason IMO that it should be maybe provided by neovim directly, then the integration would be better overall + no need for external dependencies (not everyone who uses vim uses or needs JavaScript) but all of them will benefit from this

**Comment by norcalli** [comment]
I think if we wanted to provide an LSP style diagnostic, we could do it via treesitter, so we could wait for that to settle and then see.
