### ISSUE TITLE
add diagnostics to quicklist

### ISSUE THREAD

**Issue by teto** [neovim/nvim-lsp#69]
hi,

Some things I miss from coc.nvim:
- having whole project diagnostics open in the quickfix
- file specific diagnostics in locationlist

Then I suppose this is out of scope for the plugin, but coc.nvim has mappings to go to next diagnostic from current line. In case you have such a snippet, I am eager :p

**Comment by norcalli** [comment]
Here's a snippet for how to do it for *all servers* by changing the default callback. You could also do this on a per client level with `setup { callbacks = { ["textDocument/publishDiagnostics"] = ... } }`

```lua
do
  local method = 'textDocument/publishDiagnostics'
  local default_callback = vim.lsp.callbacks[method]
  vim.lsp.callbacks[method] = function(err, method, result, client_id)
    default_callback(err, method, result, client_id)
    if result and result.diagnostics then
      for _, v in ipairs(result.diagnostics) do
        v.uri = v.uri or result.uri
      end
      vim.lsp.util.set_qflist(result.diagnostics)
    end
  end
end
```

The reason I set loop and set uri is because `set_qflist` expects a list of `Location`s and the diagnostics usually are set for a single (in this case the current) file.

**Comment by justinmk** [comment]
is `textDocument/publishDiagnostics` sent passively, or does it require some request to be sent first?

**Comment by norcalli** [comment]
It's a notification, which means server sent one way communique.

**Comment by justinmk** [comment]
I could imagine a notification being trigger by a user action. But it sounds like that's not the case for `textDocument/publishDiagnostics`.

**Comment by teto** [comment]
thanks for the snippet. Seems like it stopped working (callback member disappeared ?).
Also the snippet displayed the buffer line in quickfix rather than the error (more useful, especially when the screen is too narrow to display the virtualtext).

**Comment by norcalli** [comment]
@teto could you expand on what "callback member disappeared" means? The specific error message would be good.

And yeah, that's a good point, the `set_qflist` was something I designed originally for locations and didn't consider that they could be reused with custom messages (such as from diagnostics). I'll see about adding that as a modification of the utility function or in addition to it.

If you're interested in doing it yourself and maybe contributing to neovim builtin lsp, I would recommend looking at thttps://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/util.lua#L595 for how it's currently being implemented. The simplest modification would be to make the line that reads `text = line` to consider the custom message in `row`.

**Comment by teto** [comment]
nevermind it worked again. thanks for the pointer. I might have a look, I have a few PRs in the pipeline I would liketo merge first.

**Comment by teto** [comment]
works now on master ty.

**Comment by donotnoot** [comment]
@norcalli thanks for the snippet!!!
@teto I use vim-qf to "tame the quickfix" as the plugin claims, this is what I've come up that is very similar to coc
```
Plug 'romainl/vim-qf'

...

nmap <leader>qq	<Plug>(qf_qf_toggle)
nmap qn			<Plug>(qf_qf_next)
nmap qp			<Plug>(qf_qf_previous)

```

**Comment by sparkcanon** [comment]
@norcalli thanks for your snippet! It actually creates multiple quick lists with the same diagnostics. I don't suppose it should do that. A single quick fix list should be created for project-wide diagnostics and I assume multiple location lists for several buffers.
I am very new to Lua, although I have found it to be easier to understand and write. Here is my [lua config](https://github.com/sparkcanon/nvim/tree/nvim-lsp/lua). I would really appreciate some pointers to achieve this.

**Comment by dlukes** [comment]
Thank you for the snippet! However, either `set_qflist` has changed, or the format of the diagnostics tables, so I had to tweak it a little bit to get it to work:

```lua
do
  local method = "textDocument/publishDiagnostics"
  local default_callback = lsp.callbacks[method]
  lsp.callbacks[method] = function(err, method, result, client_id)
    default_callback(err, method, result, client_id)
    if result and result.diagnostics then
      for _, v in ipairs(result.diagnostics) do
        v.bufnr = client_id
        v.lnum = v.range.start.line + 1
        v.col = v.range.start.character + 1
        v.text = v.message
      end
      lsp.util.set_qflist(result.diagnostics)
    end
  end
end
```

If anyone else ends up needing to tweak this: figure out the structure of the diagnostics tables by putting `print(vim.inspect(v))` inside the for loop (you might have to run `:messages` to display the results). Run `:help setqflist` to see what keys you need to set.

**Comment by tekannor** [comment]
Thanks for the snippets! I had some warning due to an incorrect `bufnr`, but managed to bypass it by setting `v.bufnr = vim.uri_to_bufnr(result.uri)` instead of `client_id`.

**Comment by mjlbach** [comment]
@tekannor you might be interested in :help vim.lsp.diagnostic.set_loclist()

**Comment by willmcpherson2** [comment]
To any googlers, the above snippet won't work and you'll need this:

```lua
do
  local method = "textDocument/publishDiagnostics"
  local default_callback = vim.lsp.handlers[method]
  vim.lsp.handlers[method] = function(err, method, result, client_id)
    default_callback(err, method, result, client_id)
    if result and result.diagnostics then
      for _, v in ipairs(result.diagnostics) do
        v.bufnr = client_id
        v.lnum = v.range.start.line + 1
        v.col = v.range.start.character + 1
        v.text = v.message
      end
      vim.lsp.util.set_qflist(result.diagnostics)
    end
  end
end
```

**Comment by onsails** [comment]
I've created a plugin for rendering workspace diagnostics in quickfix and live updating it as diagnostics changes: https://github.com/onsails/vimway-lsp-diag.nvim

**Comment by benelan** [comment]
Here is the snippet updated for 2024:

```lua
do
  local method = "textDocument/publishDiagnostics"
  local default_handler = vim.lsp.handlers[method]

  vim.lsp.handlers[method] = function(err, result, ctx, config)
    default_handler(err, result, ctx, config)

    if result and result.diagnostics then
      for _, v in ipairs(result.diagnostics) do
        v.bufnr = ctx.bufnr
        v.lnum = v.range.start.line + 1
        v.col = v.range.start.character + 1
        v.text = v.message
      end

      vim.fn.setqflist(vim.diagnostic.toqflist(result.diagnostics))
    end
  end
end
```

That will only add diagnostics from LSPs, so anything from nvim-lint, null-ls, etc. will not be included. 

If you want all diagnostics, you can use this keymap:
```lua
vim.keymap.set(
  "n",
  "gQ",
  function() vim.fn.setqflist(vim.diagnostic.toqflist(vim.diagnostic.get())) end,
  { noremap = true, desc = "Add all diagnostics to quickfix" }
)
```

Or do it in an autocmd:

```lua
vim.api.nvim_create_autocmd({ "InsertLeave", "BufWritePost" }, {
  callback = function()
    vim.fn.setqflist(vim.diagnostic.toqflist(vim.diagnostic.get()))
  end,
})
