### ISSUE TITLE
Is it possible to pass in an array of paths into root_dir?

### ISSUE THREAD

**Issue by Kraust** [neovim/nvim-lsp#77]
I am working with a pre-1.13 go codebase that doesn't use go modules, and I was wondering if I could pass in my own fixed set of directories into root_dir.

**Comment by justinmk** [comment]
yes, see https://github.com/neovim/nvim-lsp/blob/b5686c624c46bf0ea43278493970e45a3722393c/lua/nvim_lsp/solargraph.lua#L9

found by searching:

https://github.com/neovim/nvim-lsp/search?q=root_dir&unscoped_q=root_dir
