### ISSUE TITLE
error while calling lua chunk attempt to index upvalue 'fn' ( a nil value ) at startup

### ISSUE THREAD

**Issue by ephemerr** [neovim/nvim-lsp#81]
Ubuntu 18.04 
nvim-lsp from master branch
nvim 0.4.3 appimage from neovim.io 

error:
~/.vim/bundle/nvim-lsp/lua/nvim_lsp/util.lua:315: attempt to index local 'fn' (a nil value)

**Comment by h-michael** [comment]
nvim-lsp require nightly build nvim.

**Comment by justinmk** [comment]
There is an appimage for nightly (0.5 prerelease) as well as stable (0.4.3). 

Both are listed at https://github.com/neovim/neovim/releases
