### ISSUE TITLE
LspInstall tsserver fails

### ISSUE THREAD

**Issue by kyle-mccarthy** [neovim/nvim-lsp#93]
I am having issues installing the LSP for tsserver using the `:LspInstall tsserver` command.

```
npm WARN saveError ENOENT: no such file or directory, open '/../.cache/nvim/nvim_lsp/tsserver/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/../.cache/nvim/nvim_lsp/tsserver/package.json'
npm WARN tsserver No repository field.
npm WARN tsserver No README data
npm WARN tsserver No license field.
```

The folder exists but only has the lock file.
```
nvim/nvim_lsp/tsserver 
> ls                                                     
node_modules      package-lock.json
``` 

- NVIM v0.5.0-013436c99

I am not sure how to check the version of nvim-lsp, but I use plug and it says that it is up to date. LMK if I can provide additional debug info!

**Comment by kyle-mccarthy** [comment]
Okay so running `:LspInstall tsserver` again results in it telling me that tsserver is already installed? So I guess that the error doesn't indicate a total failure... I will close the issue.

**Comment by justinmk** [comment]
Yeah that just looks like NPM noise.
